# Hand digit classifier 
---
## Incremental network quantization

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import torchvision
from skimage import io

### Importing MNIST dataset

In [ ]:
transform = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor(),
])

train_data = torchvision.datasets.MNIST(root='../', train=True, download=True, transform=transform)
test_set = torchvision.datasets.MNIST(root="../", train=False, download=True, transform=transform)

train_set = [train_data[i] for i in range(50000)]
validation_set = [train_data[i] for i in range(50000, 60000)]

### Setting up data loaders

In [ ]:
train_loader = torch.utils.data.DataLoader(train_set, batch_size=64, shuffle=True, num_workers=2)
validation_loader = torch.utils.data.DataLoader(validation_set, batch_size=64, shuffle=False, num_workers=2)
test_loader = torch.utils.data.DataLoader(test_set, batch_size=64, shuffle=False, num_workers=2)

### Definig a VGG-7 inspired architecture model
---
Featuring 4 convolutional and 3 fully connected layers

In [2]:
class VGG7(nn.Module):
    def __init__(self):
        super(VGG7, self).__init__()
        self.conv1 = nn.Conv2d(1, 64, 3, padding="same", stride=1, bias=False)
        self.conv2 = nn.Conv2d(64, 64, 3, padding="same", stride=1, bias=False)
        self.conv3 = nn.Conv2d(64, 128, 3, padding="same", stride=1, bias=False)
        self.conv4 = nn.Conv2d(128, 128, 3, padding="same", stride=1, bias=False)
        
        self.fc1 = nn.Linear(7*7*128, 512, bias=False)
        self.fc2 = nn.Linear(512, 256, bias=False)
        self.fc3 = nn.Linear(256, 10, bias=False)

    def forward(self, x): 
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = F.max_pool2d(x, 2, stride=2)

        x = self.conv3(x)
        x = F.relu(x)
        x = self.conv4(x)
        x = F.relu(x)
        x = F.max_pool2d(x, 2, stride=2)  

        x = x.view(-1, 7*7*128)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        x = F.relu(x)
        x = self.fc3(x)  

        x = F.log_softmax(x, dim=1)  

        return x

### Utility functions

In [ ]:
def evaluateModel(net, test_loader):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    net.to(device)
    net.eval()

    correct = 0
    loss = 0
    confusion_matrix = np.zeros((10, 10))

    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = net(data)
            pred = output.max(1, keepdim=True)[1]
            correct += pred.eq(target.view_as(pred)).sum().item()
            loss += F.nll_loss(output, target, reduction="sum").item()
            confusion_matrix[pred.view(-1), target] += 1

    print("[OK] Model evaluation complete [OK]")
    print("Average loss: {:.5f}".format(loss/len(test_loader.dataset)))
    print("Test data accuracy: {:.2f}%".format(100.*(correct/len(test_loader.dataset))))

    fig, ax = plt.subplots()
    ax.imshow(confusion_matrix/len(train_loader.dataset))
    ax.set_xticks(np.arange(10))
    ax.set_yticks(np.arange(10))
    ax.set_xlabel("Truth")
    ax.set_ylabel("Predictions")
    ax.set_title("Confusion matrix")
    fig.set_size_inches(4, 4)

### Shift Quantization operations

In [ ]:
def getBounderyExponents(W, b):
    s = torch.max(torch.abs(W)).item()
    n1 = np.floor(np.log2(4*(s/3)))
    n2 = n1 + 1 - (2**(b - 1))/2
    return n1, n2

def getQuantizationMask(W, percentage, T):
    w = W.view(-1)
    t = T.view(-1)
    idx = t == 1

    numberOfWeights = w.size(dim=0)
    numberOfQWeights = int(percentage*numberOfWeights - t[idx].size(dim=0))

    t_aux = torch.Tensor(np.ones_like(T)).view(-1)
    w = w*(t_aux - t)
    w = torch.abs(w)
    sorted_w, indices_w = w.sort()
    t[indices_w[-numberOfQWeights:]] = 1
    
    return t.view(T.size())

def quantizeWeights(W, T, n1, n2):
    T_aux = torch.Tensor(np.ones_like(T))
    eps = 1e-6
    W1 = W*(T_aux - T)
    idx = W == 0
    W.data[idx] = eps

    closestExp = torch.floor(torch.log2(torch.abs(W*4/3)))
    Q = W1 + torch.sign(W)*(2**closestExp)*T

    idx = closestExp*T < n2
    Q[idx] = 0
    idx = ((closestExp > n1)*T).bool()
    Q[idx] = 2**n1

    return closestExp, Q

def quantize_conv_layer(W, T, percentage, number_of_bits):
    n = T.size(dim=0)
    m = T.size(dim=1)

    n1, n2 = getBounderyExponents(W, number_of_bits)

    for i in range(n):
        for j in range(m):
            T[i, j, :, :] = getQuantizationMask(W[i, j, :, :], percentage, T[i, j, :, :])
            _, W.data[i, j, :, :] = quantizeWeights(W[i, j, :, :], T[i, j, :, :], n1, n2)

### Device initialization for training

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
net = torch.load("../Baseline/baseline.pth")
net.to(device)

optimizer = optim.SGD(net.parameters(), lr = 1e-2, weight_decay=0)

quantization_percentages = [0.5, 0.75, 0.875]
quantization_precision = 8

epochs = 5
logs_interval = 100
iteration = 0
train_loss = []

Tconv1 = torch.zeros_like(net.conv1.weight)
Tconv2 = torch.zeros_like(net.conv2.weight)
Tconv3 = torch.zeros_like(net.conv3.weight)
Tconv4 = torch.zeros_like(net.conv4.weight)

net.train()

for q_stage, percentage in enumerate(quantization_percentages):
    # quantize layers
    quantize_conv_layer(net.conv1.weight, Tconv1, percentage, quantization_precision)
    quantize_conv_layer(net.conv2.weight, Tconv2, percentage, quantization_precision)
    quantize_conv_layer(net.conv3.weight, Tconv3, percentage, quantization_precision)
    quantize_conv_layer(net.conv4.weight, Tconv4, percentage, quantization_precision)
    
    # correct remaining weights by training
    for epoch in range(epochs):
        for batch_idx, (data, target) in enumerate(train_loader):
            data, target = data.to(device), target.to(device)
            optimizer.zero_grad()
            output = net(data)
            loss = F.nll_loss(output, target)
            loss.backward()

            # setam gradienti la 0
            Tconv1_aux = torch.ones_like(Tconv1)
            Tconv2_aux = torch.ones_like(Tconv2)
            Tconv3_aux = torch.ones_like(Tconv3)
            Tconv4_aux = torch.ones_like(Tconv4)
            net.conv1.weight.grad = net.conv1.weight.grad*(Tconv1_aux - Tconv1)
            net.conv2.weight.grad = net.conv2.weight.grad*(Tconv2_aux - Tconv2)
            net.conv3.weight.grad = net.conv3.weight.grad*(Tconv3_aux - Tconv3)
            net.conv4.weight.grad = net.conv4.weight.grad*(Tconv4_aux - Tconv4)

            optimizer.step()

            iteration = iteration + 1
            if iteration % logs_interval == 0:
                print('Quantization step: {}/{}, Train epoch:{}, batch index:{}, loss:{}'.format(
                    q_stage + 1, len(quantization_percentages),
                    epoch, batch_idx, loss.item()/logs_interval))
                train_loss.append(loss.item())    

quantize_conv_layer(net.conv1.weight, Tconv1, 1, quantization_precision)
quantize_conv_layer(net.conv2.weight, Tconv2, 1, quantization_precision)
quantize_conv_layer(net.conv3.weight, Tconv3, 1, quantization_precision)
quantize_conv_layer(net.conv4.weight, Tconv4, 1, quantization_precision) 

torch.save(net, "INQ.pth")

In [ ]:
evaluateModel(net, test_loader)

In [ ]:
W = torch.tensor(np.array([
    [0.01, 0.02, -0.2, 0.04, 0.33],
    [0.17, -0.42, -0.33, 0.02, -0.05], 
    [0.02, 0.83, -0.03, 0.03, 0.06],
    [-0.9, 0.07, 0.11, 0.87, -0.36], 
    [-0.73, 0.41, 0.42, 0.39, 0.47]]))
bit_length = 4
n1, n2 = getBounderyExponents(W, bit_length)
print(n1, n2)
T = torch.Tensor(np.zeros_like(W))
T = getQuantizationMask(W, 0.5, T)
print(T)
_, W = quantizeWeights(W, T, n1, n2)

W = torch.Tensor(np.array([
    [0.11, 0.04, -0.7, 0.19, -0.25],
    [0.15, -0.5, -0.25, -0.09, -0.02],
    [-0.02, 1, -0.06, 0.21, 0.15],
    [-1, 0.27, -0.09, 1, -0.25],
    [-0.5, 0.5, 0.5, 0.5, 0.5]
]))

T = getQuantizationMask(W, 0.75, T)
_, W = quantizeWeights(W, T, n1, n2)
print(T)
print(W)

In [ ]:
number_of_bits = 32
mb_conv = 1.25e-7
number_of_quantized_bits = 5
number_of_weights = 0
model_size = 0

for param in net.parameters():
    nr_weight_layer = 1
    for n in param.size():
        nr_weight_layer *= n
    number_of_weights += nr_weight_layer

model_size = number_of_weights*number_of_bits

print("Numer of weights: "+str(number_of_weights))
print("Size needed to store the model with float32 precision: {:.3f} MB".format(model_size*mb_conv))

model_size = number_of_weights*number_of_quantized_bits
print("Size needed to store the model with {} bits quantization: {:.3f} MB".format(number_of_quantized_bits, model_size*mb_conv))       

In [ ]:
#TO DO
#time reduction with quantization

In [31]:
net=VGG7()
print(net.fc3.weight.size())
net.fc1.weight[:,0]

W=torch.Tensor(np.random.randn(10))*10

values,index=w_sort

values
index

W.view(-1)




torch.Size([10, 256])


tensor([ -6.5783,  16.3643,  -2.1486,   4.3815,  -2.9944,  -6.8572,  11.7657,
         -9.4291, -16.7526,  -8.7819])

In [144]:
w_abs=torch.abs(W)
values_sort,indexes_sort=torch.sort(w_abs,descending=True)


print(indexes_sort)

number=5

T= torch.Tensor(np.zeros_like(W))

print(T)

percentaje=0.5
k=np.floor((len(w_abs)*percentaje)) #cate elem luam in fs de %
print(k)

getindexu=indexes_sort[:int(k)]


for i in range(len(getindexu)):
    T[getindexu[i]]=1

    
print(W,T)



print(values_sort)








tensor([8, 1, 6, 7, 9, 5, 0, 3, 4, 2])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
5.0
tensor([ -6.5783,  16.3643,  -2.1486,   4.3815,  -2.9944,  -6.8572,  11.7657,
         -9.4291, -16.7526,  -8.7819]) tensor([0., 1., 0., 0., 0., 0., 1., 1., 1., 1.])
tensor([16.7526, 16.3643, 11.7657,  9.4291,  8.7819,  6.8572,  6.5783,  4.3815,
         2.9944,  2.1486])


In [165]:
T= torch.Tensor(np.zeros_like(W))  #  DE AICI IEI BA

def GetZaMask(In,percentage,T):
    Ax= torch.Tensor(np.zeros_like(W))

    for i in range(len(In)):
    
     Ax[i]=torch.where(T[i]==0,In[i],0)

    w_abs=torch.abs(Ax)
    values_sort,indexes_sort=torch.sort(w_abs,descending=True)

    #k=np.floor((len(w_abs)*percentage)) #cate elem luam in fs de % si de c ati de 1 avem(ce procent am avut anterior)

    count = torch.sum(T == 1)
    
    k=np.floor(len(ex)*perc)-count
    k=int(k)

    if k <0:
      k=0

    sorted_indexes=indexes_sort[:int(k)]

    for i in range(len(sorted_indexes)):
        
        T[sorted_indexes[i]]=1

    return T
    




0
1
2
3
4
tensor([0., 1., 0., 0., 0., 1., 1., 1., 1., 0.])
tensor([8, 1, 6, 7, 9, 5, 0, 3, 4, 2])
tensor([ -6.5783,  16.3643,  -2.1486,   4.3815,  -2.9944,  17.0000,  11.7657,
         -9.4291, -16.7526,  -8.7819])


In [209]:
T

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [205]:
var= torch.Tensor ([2,0,1,5,7,12,3,90,11,4])
T= torch.Tensor(np.zeros_like(var))

GetZaMask(var,0.5,T)




0
1
2
3
4


tensor([0., 0., 0., 1., 1., 1., 0., 1., 1., 0.])

In [208]:
var= torch.Tensor ([3,4,1,5,7,12,2,90,11,0])
GetZaMask(var,1,T)

0
1
2
3
4
5
6
7
8
9


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [181]:
A=torch.Tensor([11,9,3,43,6,22,3,0,89,76])
B=torch.Tensor([1,0,0,0,0,0,0,0,1,1])
Am= torch.Tensor(np.zeros_like(A))
Z= torch.Tensor(np.zeros_like(A))


for i in range(len(B)):
    
    Am[i]=torch.where(B[i]==0,A[i],0)

print(Am)

GetZaMask(Am,0.3,Z)
# t ul ultim se aduna la ala initial

tensor([ 0.,  9.,  3., 43.,  6., 22.,  3.,  0.,  0.,  0.])
0
1
2


tensor([0., 1., 0., 1., 0., 1., 0., 0., 0., 0.])

In [201]:
# nr corect de elem ce trebe facute 1

ex=torch.Tensor([1,0,0,0,0,0,1,1,1,1])
count = torch.sum(ex == 1)
perc=1
elems=np.floor(len(ex)*perc)-count
elems=int(elems)

if elems <0:
    elems=0


print(elems)


5


In [203]:
print(T)

tensor([0., 0., 0., 1., 1., 1., 0., 1., 1., 0.])
